src/main/java/org/yidu/novel/dto/ArticleDTO.java
package org.yidu.novel.dto;

import org.yidu.novel.entity.TArticle;

public class ArticleDTO extends TArticle {

    private static final long serialVersionUID = 1386921210616354787L;

    public String getIntroOmit() {
        if (getIntro() != null && getIntro().length() > 60) {
            return getIntro().substring(0, 60) + "...";
        }
        return getIntro();
    }

    public String getLastchapterOmit() {
        if (getLastchapter() != null && getLastchapter().length() > 10) {
            return getLastchapter().substring(0, 10);
        }
        return getLastchapter();
    }

    public final static class ArticleType {

        /**
         * 1|玄幻魔法
         */
        public final static int XUANHUAN = 1;
        /**
         * 2|武侠修真
         */
        public final static int WUXIA = 2;
        /**
         * 3|都市言情
         */
        public final static int YANXIN = 3;
        /**
         * 4|历史军事
         */
        public final static int JUSHI = 4;
        /**
         * 5|侦探推理
         */
        public final static int ZHENTAN = 5;
        /**
         * 6|网游动漫
         */
        public final static int WANGYOU = 6;
        /**
         * 7|科幻灵异
         */
        public final static int KEHUAN = 7;
        /**
         * 8|恐怖灵异
         */
        public final static int KONGBU = 8;
        /**
         * 9|剧本其他
         */
        public final static int JUBEN = 9;
        /**
         * 10|其他类型
         */
        public final static int OTHER = 10;
    }

}

src/main/java/org/yidu/novel/entity/TArticle.java
package org.yidu.novel.entity;

// Generated 2013/12/26 20:57:47 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import org.apache.commons.lang3.StringEscapeUtils;
import org.apache.commons.lang3.StringUtils;
import org.yidu.novel.constant.YiDuConfig;
import org.yidu.novel.constant.YiDuConstants;

/**
 * TArticle generated by hbm2java
 */
public class TArticle implements java.io.Serializable {

    private static final long serialVersionUID = -4668183129971625875L;
    private int articleno;
    private String articlename;
    private String initial;
    private String keywords;
    private Integer authorid;
    private String author;
    private Integer category;
    private Integer subcategory;
    private String intro;
    private Integer lastchapterno;
    private String lastchapter;
    private Integer chapters;
    private Integer size;
    private Boolean fullflag;
    private Integer imgflag;
    private Date postdate;
    private Date lastupdate;
    private Boolean firstflag;
    private Integer permission;
    private Boolean authorflag;
    private String agent;

    private Integer dayvisit;
    private Integer weekvisit;
    private Integer monthvisit;
    private Integer allvisit;
    private Integer dayvote;
    private Integer weekvote;
    private Integer monthvote;
    private Integer allvote;

    private Boolean deleteflag;
    private Integer publicflag;

    private Integer modifyuserno;
    private Date modifytime;

    public TArticle() {
    }

    public TArticle(int articleno) {
        this.articleno = articleno;
    }

    public int getArticleno() {
        return this.articleno;
    }

    public void setArticleno(int articleno) {
        this.articleno = articleno;
    }

    public String getArticlename() {
        return this.articlename;
    }

    public void setArticlename(String articlename) {
        this.articlename = articlename;
    }

    public String getInitial() {
        return initial;
    }

    public void setInitial(String initial) {
        this.initial = initial;
    }

    public String getKeywords() {
        return this.keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    public Integer getAuthorid() {
        return this.authorid;
    }

    public void setAuthorid(Integer authorid) {
        this.authorid = authorid;
    }

    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Integer getCategory() {
        return this.category;
    }

    public void setCategory(Integer category) {
        this.category = category;
    }

    public Integer getSubcategory() {
        return subcategory;
    }

    public void setSubcategory(Integer subcategory) {
        this.subcategory = subcategory;
    }

    public String getIntro() {
        return this.intro;
    }

    public String getIntroForHtml() {
        if (intro != null) {
            // 替换换行和空格
            String html = StringEscapeUtils.escapeHtml4(intro);
            return html.replaceAll("\r\n", "<br/>").replaceAll("\n", "<br/>").replaceAll("\\s", "&nbsp;");
        }
        return null;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

    public Integer getLastchapterno() {
        return this.lastchapterno;
    }

    public void setLastchapterno(Integer lastchapterno) {
        this.lastchapterno = lastchapterno;
    }

    public String getLastchapter() {
        return this.lastchapter;
    }

    public void setLastchapter(String lastchapter) {
        this.lastchapter = lastchapter;
    }

    public Boolean getFirstflag() {
        return firstflag;
    }

    public void setFirstflag(Boolean firstflag) {
        this.firstflag = firstflag;
    }

    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    public Integer getPermission() {
        return permission;
    }

    public Boolean getAuthorflag() {
        return authorflag;
    }

    public void setAuthorflag(Boolean authorflag) {
        this.authorflag = authorflag;
    }

    public Integer getChapters() {
        return this.chapters;
    }

    public void setChapters(Integer chapters) {
        this.chapters = chapters;
    }

    public Integer getSize() {
        return this.size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }

    public Boolean getFullflag() {
        return this.fullflag;
    }

    public void setFullflag(Boolean fullflag) {
        this.fullflag = fullflag;
    }

    public Integer getImgflag() {
        return this.imgflag;
    }

    public void setImgflag(Integer imgflag) {
        this.imgflag = imgflag;
    }

    public Date getPostdate() {
        return this.postdate;
    }

    public void setPostdate(Date postdate) {
        this.postdate = postdate;
    }

    public Date getLastupdate() {
        return this.lastupdate;
    }

    public String getAgent() {
        return agent;
    }

    public void setAgent(String agent) {
        this.agent = agent;
    }

    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    public Integer getDayvisit() {
        return this.dayvisit;
    }

    public void setDayvisit(Integer dayvisit) {
        this.dayvisit = dayvisit;
    }

    public Integer getWeekvisit() {
        return this.weekvisit;
    }

    public void setWeekvisit(Integer weekvisit) {
        this.weekvisit = weekvisit;
    }

    public Integer getMonthvisit() {
        return this.monthvisit;
    }

    public void setMonthvisit(Integer monthvisit) {
        this.monthvisit = monthvisit;
    }

    public Integer getAllvisit() {
        return this.allvisit;
    }

    public void setAllvisit(Integer allvisit) {
        this.allvisit = allvisit;
    }

    public Integer getDayvote() {
        return this.dayvote;
    }

    public void setDayvote(Integer dayvote) {
        this.dayvote = dayvote;
    }

    public Integer getWeekvote() {
        return this.weekvote;
    }

    public void setWeekvote(Integer weekvote) {
        this.weekvote = weekvote;
    }

    public Integer getMonthvote() {
        return this.monthvote;
    }

    public void setMonthvote(Integer monthvote) {
        this.monthvote = monthvote;
    }

    public Integer getAllvote() {
        return this.allvote;
    }

    public void setAllvote(Integer allvote) {
        this.allvote = allvote;
    }

    public Boolean getDeleteflag() {
        return deleteflag;
    }

    public void setDeleteflag(Boolean deleteflag) {
        this.deleteflag = deleteflag;
    }

    public Integer getPublicflag() {
        return publicflag;
    }

    public void setPublicflag(Integer publicflag) {
        this.publicflag = publicflag;
    }

    public Integer getModifyuserno() {
        return modifyuserno;
    }

    public void setModifyuserno(Integer modifyuserno) {
        this.modifyuserno = modifyuserno;
    }

    public Date getModifytime() {
        return modifytime;
    }

    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    public String getIntroOmit() {
        if (getIntro() != null && getIntro().length() > 60) {
            return getIntro().substring(0, 60) + "...";
        }
        return getIntro();
    }

    public Integer getSubdir() {
        return this.articleno / YiDuConstants.SUB_DIR_ARTICLES;
    }

    public String getLastchapterOmit() {
        if (getLastchapter() != null && getLastchapter().length() > 10) {
            return getLastchapter().substring(0, 10);
        }
        return getLastchapter();
    }

    public String getImgUrl() {
        String fileName = "";
        if (imgflag == null) {
            fileName = "nocover.jpg";
        } else {
            switch (imgflag) {
            case 1:
                fileName = articleno + "s.jpg";
                break;
            case 2:
                fileName = articleno + "s.gif";
                break;
            case 3:
                fileName = articleno + "s.png";
                break;
            case 10:
                fileName = articleno + "l.jpg";
                break;
            default:
                fileName = "nocover.jpg";
                break;
            }
        }
        String imgUrl = YiDuConstants.yiduConf.getString(YiDuConfig.RELATIVE_IAMGE_PATH) + "/";
        if (StringUtils.equals("nocover.jpg", fileName)) {
            imgUrl = imgUrl + fileName;
        } else {
            imgUrl = imgUrl + articleno / YiDuConstants.SUB_DIR_ARTICLES + "/" + articleno + "/" + fileName;
        }
        return imgUrl;
    }

}

src/main/java/org/yidu/novel/action/ArticleListAction.java
package org.yidu.novel.action;

import java.util.ArrayList;
import java.util.List;

import org.apache.struts2.convention.annotation.Action;
import org.springframework.beans.BeanUtils;
import org.yidu.novel.action.base.AbstractPublicListBaseAction;
import org.yidu.novel.bean.ArticleSearchBean;
import org.yidu.novel.cache.CacheManager;
import org.yidu.novel.constant.YiDuConstants;
import org.yidu.novel.entity.TArticle;

/**
 * 
 * <p>
 * 小说列表Action
 * </p>
 * Copyright(c) 2013 YiDu-Novel. All rights reserved.
 * 
 * @version 1.0.0
 * @author shinpa.you
 */
@Action(value = "articleList")
public class ArticleListAction extends AbstractPublicListBaseAction {

    private static final long serialVersionUID = -4215796997609788238L;

    /**
     * 小说种类
     */
    private Integer category;

    /**
     * 页号
     */
    private int page;

    /**
     * 作者
     */
    private String author;

    /**
     * 完本标志
     */
    private Boolean fullflag;

    /**
     * 小说列表
     */
    List<TArticle> articleList = new ArrayList<TArticle>();

    public Integer getCategory() {
        return category;
    }

    public void setCategory(Integer category) {
        this.category = category;
    }

    public int getPage() {
        return page;
    }

    public void setPage(int page) {
        this.page = page;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public Boolean getFullflag() {
        return fullflag;
    }

    public void setFullflag(Boolean fullflag) {
        this.fullflag = fullflag;
    }

    public List<TArticle> getArticleList() {
        return articleList;
    }

    public void setArticleList(List<TArticle> articleList) {
        this.articleList = articleList;
    }

    public String getTempName() {
        return "articleList";
    }

    @Override
    protected void loadData() {
        logger.debug("loadData start.");

        ArticleSearchBean searchBean = new ArticleSearchBean();
        BeanUtils.copyProperties(this, searchBean);
        searchBean.setPageType(ArticleSearchBean.PageType.publicPage);

        pagination.setPageNumber(page == 0 ? 1 : page);
        pagination.setSortColumn("lastupdate");
        pagination.setSortOrder("DESC");

        // 总件数设置
        pagination.setPreperties(articleService.getCount(searchBean));
        searchBean.setPagination(pagination);

        articleList = CacheManager.getObject(CACHE_KEY_ARTICEL_LIST_PREFIX + searchBean.toString());
        if (articleList == null || articleList.size() == 0) {
            articleList = articleService.find(searchBean);
            CacheManager.putObject(CACHE_KEY_ARTICEL_LIST_PREFIX + searchBean.toString(), articleList);
        }
        logger.debug("normally end.");
    }

    @Override
    public int getPageType() {
        return YiDuConstants.Pagetype.PAGE_ARTICLE_LIST;
    }
}

src/main/java/org/yidu/novel/action/InfoAction.java
package org.yidu.novel.action;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.BeanUtils;
import org.yidu.novel.action.base.AbstractPublicBaseAction;
import org.yidu.novel.bean.ChapterSearchBean;
import org.yidu.novel.cache.CacheManager;
import org.yidu.novel.constant.YiDuConstants;
import org.yidu.novel.dto.ArticleDTO;
import org.yidu.novel.entity.TChapter;

/**
 * <p>
 * 小说简介页
 * </p>
 * Copyright(c) 2013 YiDu-Novel. All rights reserved.
 * 
 * @version 1.0.0
 * @author shinpa.you
 */
public class InfoAction extends AbstractPublicBaseAction {

    /**
     * 
     */
    private static final long serialVersionUID = -4215796997609788238L;

    /**
     * 小说编号
     */
    private int articleno;

    private ArticleDTO article = new ArticleDTO();

    private List<TChapter> chapterList = new ArrayList<TChapter>();

    public int getArticleno() {
        return articleno;
    }

    public void setArticleno(int articleno) {
        this.articleno = articleno;
    }

    public int getSubDir() {
        return articleno / YiDuConstants.SUB_DIR_ARTICLES;
    }

    public void setSubDir(int subDir) {
        // do nothing
    }

    public ArticleDTO getArticle() {
        return article;
    }

    public void setArticle(ArticleDTO article) {
        this.article = article;
    }

    public List<TChapter> getChapterList() {
        return chapterList;
    }

    public void setChapterList(List<TChapter> chapterList) {
        this.chapterList = chapterList;
    }

    public String getTempName() {
        return "info";
    }

    @Override
    protected void loadData() {
        logger.debug("loadData start.");
        article = CacheManager.getObject(CACHE_KEY_ARTICEL_PREFIX + articleno);
        if (article == null || article.getArticleno() == 0) {
            article = getArticleInfoByNo(articleno);
            if (article != null && article.getArticleno() != 0) {
                CacheManager.putObject(CACHE_KEY_ARTICEL_PREFIX + articleno, article);
            }
        }

        if (article != null) {
            // 取章节信息
            ChapterSearchBean searchBean = new ChapterSearchBean();
            BeanUtils.copyProperties(this, searchBean);
            chapterList = CacheManager.getObject(CACHE_KEY_CHAPTER_LIST_PREFIX + searchBean.toString());
            if (chapterList == null || chapterList.size() == 0) {
                chapterList = chapterService.find(searchBean);
                if (chapterList != null && chapterList.size() != 0) {
                    CacheManager.putObject(CACHE_KEY_CHAPTER_LIST_PREFIX + searchBean.toString(), chapterList);
                }
            }
        } else {
            addActionError(getText("errors.not.exsits.article"));
        }
        if (articleno != 0) {
            articleService.updateVisitStatistic(articleno);
        }
        logger.debug("loadData normally end.");
    }

    @Override
    public int getPageType() {
        // TODO Auto-generated method stub
        return YiDuConstants.Pagetype.PAGE_ARTICLE_INFO;
    }

}

src/main/java/org/yidu/novel/action/base/AbstractAdminBaseAction.java
package org.yidu.novel.action.base;

import org.apache.struts2.interceptor.validation.SkipValidation;

import com.opensymphony.xwork2.Action;

/**
 * <p>
 * 管理画面的基类
 * </p>
 * Copyright(c) 2013 YiDu-Novel. All rights reserved.
 * 
 * @version 1.0.0
 * @author shinpa.you
 */
public abstract class AbstractAdminBaseAction extends AbstractBaseAction {

    private static final long serialVersionUID = 4900892616460135567L;
    /**
     * 命名空间。
     */
    public static final String NAMESPACE = "/admin";

    protected abstract void loadData();

    @Override
    @SkipValidation
    public String execute() {
        logger.debug("execute start.");
        initCollections(new String[] { "collectionProperties.article.category" });
        loadData();
        if (this.hasErrors()) {
            logger.debug("execute abnormally end.");
            return ADMIN_ERROR;
        }
        logger.debug("execute normally end.");
        return Action.INPUT;
    }

}

src/main/webapp/themes/default/articleList.ftl
<#include "common.ftl"/>

<#macro titleContent>  
<#if category?? >
<title>${categorymap[category?c]}小说|${getText("label.system.title")}</title>
<meta name="keywords" content="${categorymap[category?c]},${categorymap[category?c]}小说,${getText("label.system.siteKeywords")}" />
<#elseif author?? >
<title>${author}的小说|${getText("label.system.title")}</title>
<meta name="keywords" content="${author}的小说,${getText("label.system.siteKeywords")}" />
<meta name="description" content="${getText("label.system.siteDescription")}" />
<#else>
<title>完本小说|${getText("label.system.title")}</title>
<meta name="keywords" content="完本小说,"${getText("label.system.siteKeywords")}" />
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#if>
</#macro>


<#macro content>
<#if adEffective?? && adEffective>
<script type="text/javascript" src="${contextPath}/ad/list1.js"></script>
</#if>
<div class="mainnav" id="navList">
<div class="main-index">位置： <a href="#"><#if fullflag ?? && fullflag>全本小说<#elseif category ??>${categorymap[category?c]}<#else>${author}的小说</#if></a></div>
    <section class="section board-list board-list-collapse">
    <ul class="seeWell cf">
        <#list articleList as article>
        <li>
           <a href="${encodeURL("/info?subdir=${article.subdir?c}&articleno=${article.articleno?c}")}"  title="${article.articlename}" class="l mr10">
                <img src="${article.imgUrl}" style="width: 120px; height: 150px"/></a>
           <#if article.fullflag ><img src="${contextPath}/themes/${themeName}/images/only.png" class="topss png_bg"><#else><img src="${contextPath}/themes/${themeName}/images/only2.png" class="topss png_bg"></#if>
           <span class="l">
              <a href="${encodeURL("/info?subdir=${article.subdir?c}&articleno=${article.articleno?c}")}"  title="${article.articlename}" class="clearfix stitle">${article.articlename}</a>
              作者：<a href="${encodeURL("/articleList?author=${article.author}")}">${article.author}</a>
              <em class="c999 clearfix">${article.introForHtml}</em>
              更新：<a href="${encodeURL("/reader?subdir=${article.subdir?c}&articleno=${article.articleno?c}&chapterno=${article.lastchapterno?c}")}"  title="${article.lastchapter}">${article.lastchapterOmit}</a>
              <a href="${encodeURL("/info?subdir=${article.subdir?c}&articleno=${article.articleno?c}")}" class="readTo"  title="${article.articlename}">马上阅读</a>
           </span>
        </li>
        </#list>
    </ul>
    <#if adEffective?? && adEffective>
      <script type="text/javascript" src="${contextPath}/ad/list2.js"></script>
    </#if>  
          <div class="pages">
              <div class="pagelink" id="pagelink">
                <#if fullflag?? && fullflag>
                <#assign listurl = "/articleList?fullflag=true&page=" >
                <#assign listurlforjs = "${contextPath}/wanben/" >
                <#elseif category??>
                <#assign listurl = "/articleList?category=${category}&page=">
                <#assign listurlforjs = "${contextPath}/list/${category}/" >
                <#else>
                <#assign listurl = "/articleList?author=${author}&page=">
                <#assign listurlforjs = "${contextPath}/list/${author}/" >
                </#if>
                <em id="pagestats">${pagination.pageNumber}/${pagination.totalPages}</em>
                <a href="${encodeURL(listurl +"1")}" class="first">1</a>
                <#list pagination.pageNumberList as pagenum >
                    <#if pagenum_index == 0 && (pagenum > 1 )>
                        <a href="${encodeURL(listurl+ (pagenum-1)?c)}" class="prev">&lt;</a>
                    </#if>
                    <#if pagenum == pagination.pageNumber>
                        <strong>${pagenum?c}</strong>
                    <#else>
                        <a href="${encodeURL(listurl + pagenum?c)}"> ${pagenum?c} </a>
                    </#if>
                    <#assign mxpagenum = pagenum >
                </#list>
                <#if mxpagenum?? && (mxpagenum < pagination.totalPages)>
                     <a href="${encodeURL(listurl + (mxpagenum+1)?c)}" class="next">&gt;</a>
                </#if>
                <a href="${encodeURL(listurl + pagination.totalPages?c)}">${pagination.totalPages?c}</a>
                <kbd>
                    <input name="page" type="text" size="4" maxlength="6" onkeydown="if(event.keyCode==13){window.location='${listurlforjs}'+this.value+'.html'; return false;}" /></kbd>
             </div>
        </div>
    </section>
  </div>
  <#if adEffective?? && adEffective>
  <script type="text/javascript" src="${contextPath}/ad/list3.js"></script>
  </#if>
  </div>
</#macro>

src/main/webapp/themes/default/index.ftl
<#include "common.ftl"/>

<#macro titleContent>  
<title>${getText("label.system.title")}</title>
<meta name="keywords" content="${getText("label.system.siteKeywords")}"/>
<meta name="description" content="${getText("label.system.siteDescription")}" />
</#macro>  

<#macro recommendblock articleList id style> 
<ul class="seeWell cf" id="${id}" style="${style}">
    <#list articleList as article>
    <li>
       <a href="${encodeURL("/info?subdir=${article.subdir?c}&articleno=${article.articleno?c}")}"  title="${article.articlename}" class="l mr10">
           <img src="${contextPath}${article.imgUrl}" style="width: 120px; height: 150px"/></a>
       <#if article.fullflag ><img src="${contextPath}/themes/${themeName}/images/only.png" class="topss png_bg"><#else><img src="/images/only2.png" class="topss png_bg"></#if>
       <span class="l">
          <a href="${encodeURL("/info?subdir=${article.subdir?c}&articleno=${article.articleno?c}")}"  title="${article.articlename}" class="clearfix stitle">${article.articlename}</a>
          作者：<a href="${encodeURL("/articleList?author=${article.author}")}">${article.author}</a>
          <em class="c999 clearfix">${article.introForHtml}</em>
          更新：<a href="${encodeURL("/reader?subdir=${article.subdir?c}&articleno=${article.articleno?c}&chapterno=${article.lastchapterno?c}")}"  title="${article.lastchapter}">${article.lastchapterOmit}</a>
          <a href="${encodeURL("/info?subdir=${article.subdir?c}&articleno=${article.articleno?c}")}" class="readTo"  title="${article.articlename}">马上阅读</a>
       </span>
    </li>
    </#list>
</ul>
</#macro>

<#macro lastupdateblock articleList> 
<section class="box" id="news">
    <h2>刚刚更新的：</h2>
    <ol>
        <#list articleList as article>
            <li>
                <em class="r">${article.lastupdate?string("MM-dd HH:mm")}</em>
                <a href="${encodeURL("/articleList?category=${article.category}&page=1")}" title = "<#if article.category!=0>${categorymap[article.category?c]}</#if>">[&nbsp;<#if article.category!=0>${categorymap[article.category?c]}</#if>&nbsp;]</a>
                <a class="poptext" href="${encodeURL("/info?subdir=${article.subdir?c}&articleno=${article.articleno?c}")}"
                    title="${article.articlename}最新章节" class="f14">${article.articlename}</a>
                <a class="poptext" href="${encodeURL("/reader?subdir=${article.subdir?c}&articleno=${article.articleno?c}&chapterno=${article.lastchapterno?c}")}" ><#if article.lastchapter?? >${article.lastchapter}</#if></a>
                作者：<a class="poptext" href="${encodeURL("/articleList?author=${article.author}")}" title="${article.author}的小说" class="f14">${article.author}</a>
            </li>
        </#list>
    </ol>
</section>
</#macro>

<#macro lastinsertblock articleList> 
<section class="box" id="sorts">
    <h2>最新入库小说：</h2>
    <ol>
        <#list articleList as article>
        <li class="top3">
            <span class="order">${article_index+1}</span>
            <span class="chapter"><a href="${encodeURL("/articleList?category=${article.category}")}" title="<#if article.category!=0>${categorymap[article.category?c]}</#if>" target="_blank">[<#if article.category!=0>${categorymap[article.category?c]}</#if>]</a></span>
            <a target="_blank" href="${encodeURL("/info?subdir=${article.subdir?c}&articleno=${article.articleno?c}")}" title="${article.articlename}最新章节">${article.articlename}</a> 
            <span class="chapter"><a href="${encodeURL("/reader?subdir=${article.subdir?c}&articleno=${article.articleno?c}&chapterno=${article.lastchapterno?c}")}" title="${article.lastchapter}">${article.lastchapter}</a></span>
        </li>
        </#list>
    </ol>
</section>
</#macro>


<#macro content>
   <#if adEffective?? && adEffective>
   <script type="text/javascript" src="${contextPath}/ad/index1.js"></script>
   </#if>
   <p class="b-all-switch normal">好看的:
      <a href="javascript:;" class="select" id="ask1" onMouseOver="repales_rell1(1,5)">都市言情</a>
      <a href="javascript:;" id="ask2" onMouseOver="repales_rell1(2,5)">玄幻魔法</a>
      <a href="javascript:;" id="ask3" onMouseOver="repales_rell1(3,5)">历史军事</a>
      <a href="javascript:;" id="ask4" onMouseOver="repales_rell1(4,5)">恐怖灵异</a>
      <a href="javascript:;" id="ask5" onMouseOver="repales_rell1(5,5)">武侠修真</a>
   </p>

    <#if recommendblock?exists>
          <@recommendblock articleList=blocks.index_yanqing_tuijian id="cttd1" style=""/>
    </#if>
    <#if recommendblock?exists>
          <@recommendblock articleList=blocks.index_xuanhuan_tuijian id="cttd2" style="display:none;"/>
    </#if>
    <#if recommendblock?exists>
          <@recommendblock articleList=blocks.index_junshi_tuijian id="cttd3" style="display:none;"/>
    </#if>
    <#if recommendblock?exists>
          <@recommendblock articleList=blocks.index_kongbu_tuijian id="cttd4" style="display:none;"/>
    </#if>
    <#if recommendblock?exists>
          <@recommendblock articleList=blocks.index_wuxia_tuijian id="cttd5" style="display:none;"/>
    </#if>

    <#if adEffective?? && adEffective>
    <script type="text/javascript" src="/ad/index2.js"></script>
    </#if>
        <div id="J_random_board" class="random-board cf board">
            <#if lastupdateblock?exists>
              <@lastupdateblock articleList=blocks.last_update_list/>
            </#if>
            <#if lastinsertblock?exists>
              <@lastinsertblock articleList=blocks.last_insert_list/>
            </#if>
        </div> 
        <div class="clear"></div>
        <p class="b-all-switch normal">友情链接:</p>
        <div class="mainLink">
            ${blocks.friend_link}
        </div>
</#macro>